//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_flim.Areas.Admin.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListDV
    {
        public int ID { get; set; }
        public string NameDV { get; set; }
        public string ImageDV { get; set; }
        public Nullable<int> PhimID { get; set; }
        public string Date_of_birth { get; set; }
        public string Job { get; set; }
        public string Height { get; set; }
        public Nullable<int> View { get; set; }
        public string Related_movies { get; set; }
        public string Story { get; set; }
        public string NamePhim { get; set; }
    
        public virtual Phim Phim { get; set; }
    }
}
